server:
  # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_level: INFO

# Telegram notifications
telegram:
  bot_token: TELEGRAM_BOT_TOKEN
  chat_id: TELEGRAM_CHAT_ID

# Trading accounts
accounts:
  account-a:
    broker:
      name: tinvest
      config:
        token: tinvest_token
        account_id: tinvest_account_id
        sandbox_mode: true
  account-b:
    broker:
      name: finam
      config:
        token: finam_token
        account_id: finam_account_id
